### ISSUE TITLE
Query track data in bulk RuntimeError: Master and Return Tracks have no 'Arm' state!

### ISSUE THREAD

**Issue by StrongBearCeo** [ideoforms/AbletonOSC#115]
This didn't happen on my other live set but the Ableton Live Suite 11 Tutorial live set

`/live/song/get/track_data 0 -1 track.arm` would cause the problem

```
(2024-01-28 19:08:31,008) [INFO] Getting track data: ['track.name', 'track.color', 'track.arm', 'track.solo', 'track.has_midi_input', 'clip.name', 'clip.color', 'clip.is_playing', 'clip.is_recording', 'clip.is_midi_clip', 'clip_slot.has_clip', 'clip_slot.has_stop_button'] (tracks 0..-1)
(2024-01-28 19:08:31,022) [ERROR] AbletonOSC: Error handling OSC message: Master and Return Tracks have no 'Arm' state!
(2024-01-28 19:08:31,051) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\hv\Documents\Ableton\User Library\Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 220, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\hv\Documents\Ableton\User Library\Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 196, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\hv\Documents\Ableton\User Library\Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 147, in process_message
    rv = callback(message.params)
  File "C:\Users\hv\Documents\Ableton\User Library\Remote Scripts\AbletonOSC\abletonosc\song.py", line 133, in song_get_track_data
    value = getattr(track, property_name)
RuntimeError: Master and Return Tracks have no 'Arm' state!
```

**Comment by StrongBearCeo** [comment]
commit eb1dccd0505ce5d012ce2d205266561de9952ece
Ableton Live Suite 11.3.21

I confirm that this still happens on a fresh clone of the current `master`. All other control surface scripts were removed at the tested time.

Did you test with the Tutorial live set? i.e. Help / Built-in Lessons

**Comment by ideoforms** [comment]
Oh yes, just tested with the Tutorial set and I do indeed see the same behaviour. I've just taken a quick look, and it looks like it's because the Tutorial set has a track group within it; if I ungroup the tracks, the issue goes away. Might be to do with the way that `song.tracks` is counted...
