### ISSUE TITLE
Track API cannot get float value

### ISSUE THREAD

**Issue by Meach** [ideoforms/AbletonOSC#13]
Hi!

When I try to get the volume (/live/track/get/volume) or panning (/live/track/get/panning) of a track, I get the following error in the log file.

```
(2022-09-19 22:07:49,875) [INFO] AbletonOSC: Error handling message: Traceback (most recent call last):
  File "PATH\AbletonOSC\abletonosc\osc_server.py", line 71, in process
    self.send(message.address, rv)
  File "PATH\AbletonOSC\abletonosc\osc_server.py", line 47, in send
    for param in params:
TypeError: 'float' object is not iterable
```

I also get similar error when I try to get the send value (/live/track/get/send):
```
(2022-09-19 22:15:22,189) [INFO] AbletonOSC: Error handling message: Traceback (most recent call last):
  File "PATH\AbletonOSC\abletonosc\osc_server.py", line 71, in process
    self.send(message.address, rv)
  File "PATH\AbletonOSC\abletonosc\osc_server.py", line 47, in send
    for param in params:
TypeError: 'DeviceParameter' object is not iterable
```

**Comment by ideoforms** [comment]
Now fixed, closed by #15
