### ISSUE TITLE
live/device/set/parameters/value Error

### ISSUE THREAD

**Issue by Coupe70** [ideoforms/AbletonOSC#28]
**live/device/set/parameters/value** (to set ALL device values at once) does not work and gives an error in the log.
I tried with Abletons MIDI Pitch device which has 4 parameters and sent 
track_id, device_id, value, value, value, value (int, int, float, float, float, float).

/get/parameters/value, /get/parameter/value and also /set/parameter/value (to set ONE device value) work as expected.

(already reported by mail)

(2022-11-29 00:38:15,965) [INFO] AbletonOSC: Error handling message: Traceback (most recent call last):
  File "C:\Users\Anja\Documents\Ableton\User Library\Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 107, in process
    rv = callback(message.params)
  File "C:\Users\Anja\Documents\Ableton\User Library\Remote Scripts\AbletonOSC\abletonosc\device.py", line 14, in device_callback
    return func(device, *args, params[2:])
  File "C:\Users\Anja\Documents\Ableton\User Library\Remote Scripts\AbletonOSC\abletonosc\device.py", line 62, in device_set_parameters_value
    for index, value in params:
TypeError: cannot unpack non-iterable float object

**Comment by ideoforms** [comment]
Fixed

**Comment by Coupe70** [comment]
Fix confirmed.
